import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { getStaticPaths, makeStaticProps} from '@/lib/getStatic'
import { useTranslation } from 'next-i18next'

import LinkComponent from '../../components/Link'


const inter = Inter({ subsets: ['latin'] })


const Home = () =>{
  const { t } = useTranslation('common')

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <ul>
          <li>
            <LinkComponent href="/">{t('home')}</LinkComponent>
          </li>
          <li>
            <LinkComponent href="/about">{t('aboutUs')}</LinkComponent>
          </li>
          <li>
          <LinkComponent href="/blog/hello">{t('hello')}</LinkComponent>
          </li>
        </ul>
      </main>
    </>
  )
}

export default Home

const getStaticProps = makeStaticProps(['common']);
export { getStaticPaths, getStaticProps }